### ISSUE TITLE
REST API запрос документов, дублируется поле в транзакциях

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#50]
В описании транзакции дублируется поле type, что может приводить к некорректной работе.

Пример:
{
      "uuid":"c20784b2-5aa7-4706-94ee-3f6ab9fbafb2",
      "type":"OPEN_SESSION",
      "deviceId":"352398080143045",
      "deviceUuid":"20170310-AC51-402F-809D-92B386B8705C",
      "transactions":[
         {
            **"type":"OPEN_SESSION",**
            "uuid":null,
            "id":"1",
            **"type":"OPEN_SESSION",**
            "userCode":null,
            "userUuid":"20170310-1C08-4009-8088-86C592B6B35E",
            "creationDate":"2017-03-10T12:00:50.000+0000",
            "timezone":10800000
         }
      ],
      "closeDate":"2017-03-10T12:00:50.000+0000",
      "openDate":"2017-03-10T12:00:50.000+0000",
      "openUserCode":null,
      "openUserUuid":"20170310-1C08-4009-8088-86C592B6B35E",
      "closeUserCode":null,
      "closeUserUuid":"20170310-1C08-4009-8088-86C592B6B35E",
      "sessionUUID":"dcbb0da2-443a-4108-838e-48ef35340d09",
      "sessionNumber":"1",
      "number":1,
      "closeResultSum":null,
      "closeSum":null,
      "storeUuid":"20170310-BC86-402E-8077-2EB96F99F820",
      "completeInventory":true,
      "extras":null,
      "new":false
   }

**Comment by capcom6** [comment]
Вот вообще чудесный документ, получившийся после печати X-отчета (кассового отчета):
{
      "uuid":"fec12911-c760-4a72-a2c4-1d817bf420b0",
      "type":"FPRINT",
      "deviceId":"352398080143045",
      "deviceUuid":"20170310-AC51-402F-809D-92B386B8705C",
      "transactions":[
         {
            **"type":"FPRINT_Z_REPORT",**
            "uuid":null,
            "id":"75",
            **"type":"FPRINT_X_REPORT",**
            "userCode":null,
            "userUuid":"20170310-1C08-4009-8088-86C592B6B35E",
            "creationDate":"2017-03-28T02:56:51.000+0000",
            "timezone":25200000,
            "receiptNumber":33,
            "documentNumber":78,
            "sessionNumber":0,
            "proceeds":33.3,
            "cash":0,
            "total":0
         }
      ],
      "closeDate":"2017-03-28T02:56:51.000+0000",
      "openDate":"2017-03-28T02:56:51.000+0000",
      "openUserCode":null,
      "openUserUuid":"20170310-1C08-4009-8088-86C592B6B35E",
      "closeUserCode":null,
      "closeUserUuid":"20170310-1C08-4009-8088-86C592B6B35E",
      "sessionUUID":"301c9b73-e366-49b0-b2f1-bd9f2f479553",
      "sessionNumber":"5",
      "number":23,
      "closeResultSum":"33.3",
      "closeSum":"0",
      "storeUuid":"20170310-BC86-402E-8077-2EB96F99F820",
      "completeInventory":true,
      "extras":null,
      "new":false
   }

Имеем в транзакции 2 поля type с РАЗНЫМИ значениями

**Comment by Lytkini** [comment]
Добрый день.
В базе эти запросы без дублирующихся полей.
Чтобы разобраться более подробно, напишите, пожалуйста, на developers@evotor.ru.

**Comment by capcom6** [comment]
Такого адреса не существует:
Формирующий сервер: mail.evotor.local
developers@evotor.ru
#< #5.1.10 smtp;550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup> #SMTP#

**Comment by Lytkini** [comment]
Прошу прощения, опечатка.
developer@evotor.ru

**Comment by NikosHope** [comment]
Решено. Больше не воспроизводится.
