### ISSUE TITLE
REST API - запрос документов по номеру смены

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#51]
Хотелось бы увидеть возможность запроса списка документов по номеру смены.

**Comment by Lytkini** [comment]
Такая возможность не предусмотрена.
Попробуйте использовать фильтрацию по времени (параметры ltCloseDate и gtCloseDate).

**Comment by capcom6** [comment]
Тогда я крайне рекомендую добавить такую возможность в ближайшее время. Аргументов как минимум 2:

1. Среди наших клиентов нет ни одного, кто бы работал по дате-времени. Все работают посменно и сравнивают цифры бухгалтерии/товароучетном ПО с Z-отчетом, который отражает одну смену. Логично, что и загружать отчеты им будет удобнее по номеру смены.
2. Ваши конкуренты уже получают негативные отзывы из-за отсутствия подобной функции - будьте впереди них

Второй вариант - нужен запрос, который выдаст список всех смен с указанием временных интервалов каждой из них.

**Comment by NikosHope** [comment]
>Второй вариант - нужен запрос, который выдаст список всех смен с указанием временных интервалов каждой из них.
Можно выгрузить документы с фильтрацией по типам OPEN_SESSION и CLOSE_SESSION.
Это даст тот же эффект.
