### ISSUE TITLE
Документация по транзакциям

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#52]
Здравствуйте.

А есть ли документация по транзакциям в документе?
По документам документацию вижу, но там не все возможные транзакции описаны.

**Comment by Lytkini** [comment]
Добрый день.
Отдельной документации по транзакциям нет.
Описание будет доступно в рамках документов, как это сделано сейчас. В настоящий момент, как Вы справедливо заметили, описаны не все возможные транзакции. Работа над этим ведётся.

**Comment by capcom6** [comment]
Все же хотелось бы видеть отдельный справочник по транзакциям, потому что искать интересующую транзакцию по нескольким документам в надежде что она там есть - удобство ниже среднего.
Тем более что описание документов уже не соответствует местами реальности.

**Comment by NikosHope** [comment]
На данный момент примеры документов с комментариями максимально актуальны.
Каких-либо изменений в существующем протоколе до конца года не предвидится.
В конце этого - начале следующего года станет доступным новая версия протокола документов, которая содержит больше деталей от смарт-терминалов, ближе к тому виду что печатается на чеке и не использует транзакционность (что должно облегчить разработчикам обработку).
