### ISSUE TITLE
Транзакция DISCOUNT_POSITION, тип скидки

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#53]
Здравствуйте.
Подскажите, пожалуйста, как в транзакции DISCOUNT_POSITION определить тип скидки: "процентная" или "суммовая"?

В транзакции DISCOUNT_POSITION присутствует поле discountType, однако, при обоих типах скидок оно имеет значение "1".

**Comment by Lytkini** [comment]
Добрый день.
Сейчас определить тип скидки нельзя. Все скидки Эвотор переводит в "суммовые", даже если пользователь указал процент.
Поле discountType не определяет тип скидки и не предназначено для использования сторонними сервисами.
В документе Вы можете найти поля вроде discountPositionPercent. Это автоматически посчитанный процент от суммы. Например, если пользователь укажет 5%, сначала будет высчитаная сумма скидки, а потом она снова будет переведена в % для отображения в поле discountPositionPercent.

**Comment by capcom6** [comment]
Такой способ чреват погрешностями. Например, захотим мы сделать отчет по процентам скидок и увидим проценты 4,98%, 5%, 5,04%, а исходно скидка была 5% во всех случаях, и в отчете должна быть строка 5%. Пример отчета - это лишь способ объяснить проблему и к реальной задаче отношения не имеет.

**Comment by NikosHope** [comment]
Мы рекомендуем смотреть на суммовые скидки, поскольку независимо от порядка применения скидок и их размера - все денежные величины ограничивают точность размера скидки необходимостью округления до копеек.
Таким образом, наиболее точным способом - будет определять результирующий размер скидки в процентах на основе фактической суммы скидки.
