### ISSUE TITLE
Транзакция DOCUMENT_CLOSE_FPRINT, нулевой номер смены

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#54]
В транзакцию DOCUMENT_CLOSE_FPRINT почему-то попадает нулевой номер смены в поле sessionNumber, хотя в документе номер смены указан.
Возможно, это из-за нефискальности аппарата?

**Comment by Lytkini** [comment]
Пожалуйста, напишите на developers@evotor.ru.

**Comment by capcom6** [comment]
Такого адреса не существует:
Формирующий сервер: mail.evotor.local
developers@evotor.ru
#< #5.1.10 smtp;550 5.1.10 RESOLVER.ADR.RecipientNotFound; Recipient not found by SMTP address lookup> #SMTP#

**Comment by Lytkini** [comment]
Прошу прощения, опечатка.
developer@evotor.ru

**Comment by NikosHope** [comment]
>Возможно, это из-за нефискальности аппарата?

Именно так.
