### ISSUE TITLE
 Использование iframe в настройках приложения

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#56]
Здравствуйте.

Есть ли какая-то документация по использованию iframe на странице настроек приложения?
Также не работает флаг Disabled для текстовых полей.

**Comment by NikosHope** [comment]
К сожалению, документация отсутствует.
Если у вас есть какие-то вопросы по этой части - вы всегда можете задать вопрос через встроенную форму обратной связи на портале разработчика.
