### ISSUE TITLE
 Токен к REST API

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#57]
Здравствуйте.

Возник вопрос касательно токена к REST API.
Поскольку токен никак не привязывается к клиентской части (например, обработка 1С), то что мешает пользователю скачать обработку для 1С с дорогой подпиской, а потом купить самую дешевую подписку под другое приложение и использовать токен оттуда?

В итоге, разработчик исходной обработки полностью теряет доход, хотя его разработкой пользуются.

По опыту использования других API для этих целей используется еще секретный ключ приложения, который не позволит использовать токен с другим приложением. При этом обеспечение сохранности секретного ключа ложится на разработчика.

**Comment by NikosHope** [comment]
Поскольку система защиты обработок 1С от вскрытия крайне слаба - даже использование секретного ключа не защитит приложение от такого рода мошенничества.
Мы рекомендуем реализовать собственный сервер авторизации, с которым будет работать ваше клиентское приложение.
А непосредственно ключ от приложения из маркетплейса - пользователю не отображать (вместо этого можно настроить передачу ключа приложения на ваш сервер в момент установки приложения).

**Comment by RobotAvi** [comment]
Подскажите, пожалуйста, есть ли у вас в открытом доступе api для интеграции с 1с? Хочу понять, какие поля можно от вас получить, например, по номенклатуре.
