### ISSUE TITLE
REST API период запроса документов

### ISSUE THREAD

**Issue by capcom6** [evotor/documentation-api#58]
Здравствуйте.

Не удается запросить документы за период. Возвращается HTTP код 400 с пустым телом.
Используемый URL: https://api.evotor.ru/api/v1/inventories/stores/20170310-BC86-402E-8077-2EB96F99F820/documents?gtCloseDate=2017-03-27T17:00:00.000Z&ltCloseDate=2017-03-28T17:00:00.000Z

В чем может быть причина?
Правильно ли я понимаю, что время должно быть в UTC?

**Comment by vmugue** [comment]
У Вас формат даты не корректный, вместо Z должна быть временная зона, например +0300 для Москвы.
Вот так: &ltCloseDate=2017-03-28T17:00:00.000+0300
