### ISSUE TITLE
Не генерируется код по описанию OpenAPI

### ISSUE THREAD

**Issue by EsikAntony** [evotor/documentation-api#62]
Добрый день.

Есть проблема при генерации кода из описания сервиса https://lytkini.github.io/evotor-rest-api.yaml на последнем Swagger Codegene 2.2.2.

Запускаю генерацию так: 
$ java -jar swagger-codegen-cli-2.2.2.jar generate -l spring -i https://lytkini.github.io/evotor-rest-api.yaml --api-package com.ae.evotor.api --artifact-id evotor-api --group-id com.ae.evotor -v
Лог генерации: https://pastebin.com/NzaQHe0Z

В результате получаю только сваггеровский обвес для Spring MVC и всё.

В логе генерации смущает то, что после чтения конфигурации REST API Swagger не видит ссылки на paths, definitions, parameters, info: в строках 11 и 28-30 пустые объекты.

ЧЯДНТ?

**Comment by Lytkini** [comment]
Добрый день.

Такое поведение codegen связано с тем, что спецификация разделена на несколько файлов. В основном yaml'е указаны относительные пути к этим файлам.

Для проверки, я собрал всё в одном файле в своём репозитории: [ https://lytkini.github.io/evotor-rest-api.yaml](https://lytkini.github.io/evotor-rest-api.yaml). Попробуйте, получается то, что нужно или нет?
Если всё ок, буду думать, чтобы объединить спеку на сайте нашей документации - [api.evotor.ru/docs](https://api.evotor.ru/docs). В будущем, пожалуйста, используйте его, так как свой репозиторий я использую для тестирования, и версия там может отличаться от актуальной.

С уважением,
Лыткин Илья
Технический писатель

**Comment by EsikAntony** [comment]
> Для проверки, я собрал всё в одном файле в своём репозитории: https://lytkini.github.io/evotor-rest-api.yaml. Попробуйте, получается то, что нужно или нет?

Да, из одного файла исходный код генерируется, однако он получается не компилируемым.

Отчасти потому что в описании всё ещё присутствуют ссылки ($ref) на другие описания, отчасти потому что не заданы имена параметров в методах:
- partner.ru/api/v1/user/verify
- partner.ru/api/v1/user/create
- partner.ru/api/v1/user/tariff
- partner.ru/api/v1/user/token

И в перечислении measureName указаны кириллические константы.

**Comment by EsikAntony** [comment]
@Lytkini, будет ли ещё какая-нибудь помощь в решении проблем генерации кода? Или довольствоваться тем, что есть словесное описание? :)

Btw, swagger'овский редактор http://editor2.swagger.io также ругается ошибками на описание сервиса из документации: https://pastebin.com/W5aGuqty

**Comment by NikosHope** [comment]
@EsikAntony 

Мы не гарантируем возможность сборки нашей спецификации в рабочий код.
Более того, мы не рекомендовали бы такой код использовать в публичных версиях вашего ПО, даже если бы сборка происходила без проблем (о недостатках автогенерируемого кода - отдельная тема).

P.S.:
Факт наличия в enum для measureName кириллических значений - никоим образом не является проблемой документации, согласитесь? :)
